/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.screens;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author santi
 */
public class frmAvatarSelection extends javax.swing.JFrame {

    /**
     * Creates new form frmAvatarSelection
     */
    public frmAvatarSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        TituloMenor = new javax.swing.JLabel();
        elGallo = new javax.swing.JButton();
        elBorracho = new javax.swing.JButton();
        laDama = new javax.swing.JButton();
        elApache = new javax.swing.JButton();
        elValiente = new javax.swing.JButton();
        laChalupa = new javax.swing.JButton();
        elDiablito = new javax.swing.JButton();
        elSol = new javax.swing.JButton();
        unirse = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        fondoPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        fondoPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        fondoPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        Titulo.setText("Iniciar sesión");
        fondoPanel.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 60));

        TituloMenor.setBackground(new java.awt.Color(0, 0, 0));
        TituloMenor.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        TituloMenor.setText("Escoge tu avatar");
        fondoPanel.add(TituloMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 190, 30));

        elGallo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatars/El_Gallo.jpg"))); // NOI18N
        elGallo.setBorder(null);
        fondoPanel.add(elGallo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        elBorracho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatars/El_borracho.jpg"))); // NOI18N
        elBorracho.setBorder(null);
        elBorracho.setBorderPainted(false);
        elBorracho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elBorrachoActionPerformed(evt);
            }
        });
        fondoPanel.add(elBorracho, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        laDama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatars/La_dama.jpg"))); // NOI18N
        laDama.setBorder(null);
        laDama.setBorderPainted(false);
        fondoPanel.add(laDama, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        elApache.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatars/El_apache.jpg"))); // NOI18N
        elApache.setBorder(null);
        elApache.setBorderPainted(false);
        elApache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elApacheActionPerformed(evt);
            }
        });
        fondoPanel.add(elApache, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        elValiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatars/El_Valiente.jpg"))); // NOI18N
        elValiente.setBorder(null);
        elValiente.setBorderPainted(false);
        elValiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elValienteActionPerformed(evt);
            }
        });
        fondoPanel.add(elValiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        laChalupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatars/La_chalupa.jpg"))); // NOI18N
        laChalupa.setBorder(null);
        laChalupa.setBorderPainted(false);
        fondoPanel.add(laChalupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        elDiablito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatars/El_diablo.jpg"))); // NOI18N
        elDiablito.setBorder(null);
        elDiablito.setBorderPainted(false);
        fondoPanel.add(elDiablito, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        elSol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatars/El_sol.jpg"))); // NOI18N
        elSol.setBorder(null);
        elSol.setBorderPainted(false);
        fondoPanel.add(elSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, -1, -1));

        unirse.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        unirse.setText("Unirse");
        unirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unirseActionPerformed(evt);
            }
        });
        fondoPanel.add(unirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/Fondo_menu.jpg"))); // NOI18N
        fondoPanel.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elBorrachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elBorrachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elBorrachoActionPerformed

    private void elApacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elApacheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elApacheActionPerformed

    private void elValienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elValienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elValienteActionPerformed

    private void unirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unirseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unirseActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloMenor;
    private javax.swing.JButton elApache;
    private javax.swing.JButton elBorracho;
    private javax.swing.JButton elDiablito;
    private javax.swing.JButton elGallo;
    private javax.swing.JButton elSol;
    private javax.swing.JButton elValiente;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JButton laChalupa;
    private javax.swing.JButton laDama;
    private javax.swing.JButton unirse;
    // End of variables declaration//GEN-END:variables
}
